### ISSUE TITLE
'amount cannot be negative' on daiAvailable for underwater cdp

### ISSUE THREAD

**Issue by madumas** [makerdao/dai.js#173]
`cdp.daiAvailable` for an undercollaterized CDP generates the following error:

```
 Error: amount cannot be negative
           at amountToBigNumber (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\currency\dist\Currency.js:49:26)
           at CurrencyX.Currency (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\currency\dist\Currency.js:62:73)
           at new MDAI (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\currency\dist\index.js:50:132)
           at bigNumberFnResult (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\currency\dist\Currency.js:181:12)
           at CurrencyX.minus (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\currency\dist\Currency.js:194:32)
           at Object.daiAvailable (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\dai-plugin-mcd\dist\math.js:105:51)
           at ManagedCdp.get (C:\Users\madumas\WebstormProjects\testrunner\node_modules\@makerdao\dai-plugin-mcd\dist\ManagedCdp.js:286:19)
           at daiAvailable (C:\Users\madumas\WebstormProjects\testrunner\src\actions\cdpDrawMax.js:12:21)
```

**Comment by levity** [comment]
@madumas please update dai-plugin-mcd to v0.2.15-1 to get the fix for this
