### ISSUE TITLE
Failed to wipeDai or wipeAll dai to pay off debet

### ISSUE THREAD

**Issue by bentiancai629** [makerdao/dai.js#264]
I want to pay off a debet  with dai.js. Most function is ok except "wipe" and "wipeAll".

environment:  fork from the mainnet with ganche.

```async createVault() {
        const maker = await Maker.create('http', {
            plugins: [McdPlugin],
            url: HashQuark,
            privateKey: myPrivateKey
        });
        await maker.authenticate();

        const mgr = maker.service('mcd:cdpManager');
        const proxyAddress = await maker.service('proxy').currentProxy();
        const data = await mgr.getCdpIds(proxyAddress);
        const { id, ilk } = data[0]; // // e.g. id = 5, ilk = 'ETH-A'
        console.log(`vaultId: ${id}`);
        console.log(`currentAddress: ${maker.currentAddress()}`);

        const vault = await mgr.getCdp(id);
        console.log(`collateralAmount: ${vault.collateralAmount}`);
        console.log(`collateralValue: ${vault.collateralValue}`);
        console.log(`debtValue: ${vault.debtValue}`);
        console.log(`liquidationPrice: ${vault.liquidationPrice}`);
        console.log(`isSafe: ${vault.isSafe}`);

        const wipeDaiResult = await vault.wipeDai(DAI(3000));
        console.log(`wipeDaiResult: ${(wipeDaiResult)}`);

        // wipAllResult = await vault.wipeAll();
        // console.log(`wipAllResult: ${wipAllResult}`);

        return wipeDaiResult
    }

error result:
 
currentAddress: 0x90f79bf6eb2c4f870365e785982e1f101e93b906
  vaultId: 20015
  collateralAmount: 65.00 ETH
  collateralValue: 73945.95 USD
  debtValue: 1522.02 DAI
  liquidationPrice: 35.12 USD/ETH
  isSafe: true
  2021-02-20 17:45:54,663 ERROR 29330 [-/127.0.0.1/-/3888ms GET /api/makerdao/createVault] nodejs.Error: Transaction reverted without a reason
      at Object.app.context.onerror (/Users/feng/code/solidity/compound-monitor/node_modules/koa-onerror/index.js:39:24)
      at onerror (/Users/feng/code/solidity/compound-monitor/node_modules/koa/lib/application.js:165:32)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  
  pid: 29330
```

**Comment by bentiancai629** [comment]
lack of approve
