### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by madumas** [makerdao/dai.js#32]
Following the `readme`, I tried `npm start`, which failed with the following errors

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.1.0
3 info using node@v8.1.3
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:512:3)
5 verbose cwd /Users/marc-andre/WebstormProjects/dai.js
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 verbose node v8.1.3
9 verbose npm  v6.1.0
10 error missing script: start
11 verbose exit [ 1, true ]
```

**Comment by ethanbennett** [comment]
@madumas Ah, sorry about this, the readme is slightly out of date. As of v0.5.8, the smart contract explorer has been separated into its own repo. If you want to use it, you can just install v0.5.7 and it should work as outlined in the readme.

**Comment by ethanbennett** [comment]
For posterity, that's just `npm start` in the root directory (I'm removing it from the readme to avoid further confusion).
